### ISSUE TITLE
AssertionError: 40

### ISSUE THREAD

**Issue by markcoker** [rmadair/fuzzer#2]
python client.py -s 127.0.0.1 -p 12345 -t temp -s save

Traceback (most recent call last):
  File "client.py", line 8, in <module>
    from Executor import Executor
  File "C:\Users\mark\Downloads\fuzzer-master\fuzzer-master\Executor.py", line 1, in <module>
    from pydbg import *
  File "c:\Python27\lib\site-packages\pydbg__init__.py", line 41, in <module>
    from defines                 import *
  File "c:\Python27\lib\site-packages\pydbg\defines.py", line 37, in <module>
    from windows_h import *
  File "c:\Python27\lib\site-packages\pydbg\windows_h.py", line 116, in <module>
    assert sizeof(_MEMORY_BASIC_INFORMATION) == 28, sizeof(_MEMORY_BASIC_INFORMATION)
AssertionError: 40

**Comment by o0xmuhe** [comment]
32bits python and 32bits libs
